# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.srcs/sources_1/new/CLK_DIV.vhd}
  {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.srcs/sources_1/new/decoder.vhd}
  {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.srcs/sources_1/new/controller.vhd}
  {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.srcs/sources_1/new/counter.vhd}
  {C:/Users/ee-student/Downloads/Lab 5-20190502T185932Z-001/Lab 5/Lab 5.srcs/sources_1/new/stopwatch.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ee-student/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ee-student/Downloads/Nexys4DDR_Master.xdc]


synth_design -top stopwatch -part xc7a100tcsg324-1


write_checkpoint -force -noxdef stopwatch.dcp

catch { report_utilization -file stopwatch_utilization_synth.rpt -pb stopwatch_utilization_synth.pb }
